# Generated by Django 2.2 on 2019-04-17 12:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=300)),
                ('info_title', models.CharField(max_length=300, unique=True)),
                ('info_body_link', models.CharField(max_length=300, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'infomation',
            },
        ),
    ]
