# Generated by Django 2.2 on 2019-04-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomation',
            old_name='create_time',
            new_name='created_at',
        ),
    ]
