# Generated by Django 2.2 on 2019-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20190421_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='info_title',
            field=models.CharField(max_length=300),
        ),
    ]
