# Generated by Django 2.2 on 2019-05-24 05:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20190504_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=300)),
                ('release_title', models.CharField(max_length=300, unique=True)),
                ('release_date', models.CharField(max_length=300)),
                ('buy_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'releaseInfo',
            },
        ),
    ]
