# Generated by Django 2.2 on 2019-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_releaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='release_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='releaseinfo',
            unique_together={('artist_name', 'release_title', 'release_date')},
        ),
    ]
