# Generated by Django 2.2 on 2019-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20190524_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomation',
            name='info_label',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
